baseURL = 'https://www.dirkdhaenens.com/'
languageCode = 'en-us'
copyright = "Copyright © 2024 Dirk Dhaenens."

[module]
[[module.imports]]
path = 'github.com/gethinode/hinode'

[[menus.social]]
pre = "fab linkedin"
url = "https://www.linkedin.com/in/dirkdhaenens"
