baseURL = 'https://www.dirkdhaenens.com/'
languageCode = 'en-us'
title = 'Dirk Dhaenens'
theme = "github.com/rhazdon/hugo-theme-hello-friend-ng"
paginate = 1

[params]
author = "Dirk Dhaenens"
homeSubtitle = "full stack developer ~ software architect"
description = "Dirk Dhaenens personal site and blog"
keywords = "blog,developer,personal"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/dirkdhaenens"

[module]
[[module.imports]]
path = 'github.com/rhazdon/hugo-theme-hello-friend-ng'
